import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { WagmiProvider } from "@/components/providers/wagmi-provider";
import { PaymentWidgetProvider } from "@/components/providers/payment-widget-provider";
import { LazyMotionProvider } from "@/components/providers/LazyMotionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`min-h-screen bg-background text-foreground antialiased transition-colors duration-300`}
      >
        <WagmiProvider>
          <PaymentWidgetProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              disableTransitionOnChange
            >
              <LazyMotionProvider>
                {children}
              </LazyMotionProvider>
            </ThemeProvider>
          </PaymentWidgetProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
