import { getDefaultConfig } from '@rainbow-me/rainbowkit';
import { http } from 'wagmi'
import { baseSepolia, base, mainnet, polygon, optimism, arbitrum, bsc, sepolia } from 'wagmi/chains'

import {
  argentWallet,
  berasigWallet,
  bestWallet,
  bifrostWallet,
  binanceWallet,
  bitgetWallet,
  bitskiWallet,
  bitverseWallet,
  bloomWallet,
  braveWallet,
  bybitWallet,
  clvWallet,
  coin98Wallet,
  compassWallet,
  coreWallet,
  dawnWallet,
  desigWallet,
  enkryptWallet,
  foxWallet,
  frameWallet,
  frontierWallet,
  gateWallet,
  imTokenWallet,
  iopayWallet,
  kaiaWallet,
  kaikasWallet,
  krakenWallet,
  kresusWallet,
  ledgerWallet,
  magicEdenWallet,
  metaMaskWallet,
  mewWallet,
  nestWallet,
  oktoWallet,
  okxWallet,
  omniWallet,
  oneInchWallet,
  oneKeyWallet,
  paraSwapWallet,
  phantomWallet,
  rabbyWallet,
  rainbowWallet,
  ramperWallet,
  roninWallet,
  safeheronWallet,
  safepalWallet,
  safeWallet,
  seifWallet,
  subWallet,
  tahoWallet,
  talismanWallet,
  tokenaryWallet,
  tokenPocketWallet,
  trustWallet,
  uniswapWallet,
  valoraWallet,
  walletConnectWallet,
  wigwamWallet,
  xdefiWallet,
  zealWallet,
  zerionWallet,
} from "@rainbow-me/rainbowkit/wallets";
// Polygon, Ethereum, BNB, Base, Optimism, Arbitrum

export const config = getDefaultConfig({
  appName: 'Asty',
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID as string,
  chains: [
    mainnet,
    bsc,
    polygon,
    base,
    optimism,
    arbitrum,
    ...(process.env.NEXT_PUBLIC_IS_TESTNET === "true"
      ? [baseSepolia, sepolia]
      : []),
  ],
  ssr: true,
  transports: {
    [mainnet.id]: http(),
    [bsc.id]: http(),
    [polygon.id]: http(),
    [base.id]: http(),
    [optimism.id]: http(),
    [arbitrum.id]: http(),
    ...(process.env.NEXT_PUBLIC_IS_TESTNET === "true"
      ? { [baseSepolia.id]: http(), [sepolia.id]: http() }
      : []), 
  },
  wallets: [
    {
      groupName: "Popular",
      wallets: [
        metaMaskWallet,
        rainbowWallet,
        trustWallet,
        tokenPocketWallet,
        safepalWallet,
        rabbyWallet,
        ledgerWallet,
        walletConnectWallet,
        safeWallet,
        krakenWallet,
        mewWallet,
        omniWallet,
        phantomWallet,
      ],
    },
    {
      groupName: "Others",
      wallets: [
        argentWallet,
        berasigWallet,
        bestWallet,
        bifrostWallet,
        binanceWallet,
        bitgetWallet,
        bitskiWallet,
        bitverseWallet,
        bloomWallet,
        braveWallet,
        bybitWallet,
        clvWallet,
        coin98Wallet,
        compassWallet,
        coreWallet,
        dawnWallet,
        desigWallet,
        enkryptWallet,
        foxWallet,
        frameWallet,
        frontierWallet,
        gateWallet,
        imTokenWallet,
        iopayWallet,
        kaiaWallet,
        kaikasWallet,
        kresusWallet,
        magicEdenWallet,
        nestWallet,
        oktoWallet,
        okxWallet,
        oneInchWallet,
        oneKeyWallet,
        paraSwapWallet,
        rainbowWallet,
        ramperWallet,
        roninWallet,
        safeheronWallet,
        seifWallet,
        subWallet,
        tahoWallet,
        talismanWallet,
        tokenaryWallet,
        uniswapWallet,
        valoraWallet,
        wigwamWallet,
        xdefiWallet,
        zealWallet,
        zerionWallet,
      ],
    },
  ],
});

